<?php
declare(strict_types=1);
require_once '../../controller/login/bootstrap.php';
require_once '../../controller/login/koneksiDB2.php';
require_login();
$roleId = (string) $_SESSION['role'];
$flash = $_SESSION['flash'] ?? '';
unset($_SESSION['flash']);
$rows = [];
$sql = 'SELECT t.nomor_resi, i.desk_isi_paket AS nama_barang, s.nama_supir AS kurir, t.tanggal_jam_pengiriman, p.posisi_terakhir FROM transit t JOIN isi_paket i ON i.id_isi_paket = t.id_isi_paket JOIN supir s ON s.plat_nomor_kendaraan = t.plat_nomor_kendaraan JOIN posisi_paket p ON p.id_posisi_terakhir_paket = t.id_posisi_terakhir_paket ORDER BY t.tanggal_jam_pengiriman DESC, t.nomor_resi DESC';
$result = $conn2->query($sql);
if ($result) { while ($row = $result->fetch_assoc()) { $rows[] = $row; } } else { error_log('Dashboard query failed'); }
?><!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Dashboard Pengiriman</title><link rel="stylesheet" href="../../css/homepageAS/HomePageAdminStaff.css"></head>
<body><header class="topbar"><strong>Sampai Kilat</strong><span><?= e($_SESSION['username']) ?></span><form class="logout-form" method="post" action="../../controller/login/logout.php"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><button type="submit">Keluar</button></form></header><main><div class="title"><div><h1>Dashboard Pengiriman</h1><p>Daftar transit pengiriman terbaru.</p></div><div class="actions"><a class="button" href="../createDelivery/Create1.php">Buat pengiriman</a><a class="button secondary" href="../updatingDelivery/Update3.php">Update lokasi</a><?php if ($roleId === 'RL-001'): ?><button class="danger" type="button" onclick="document.getElementById('delete-dialog').showModal()">Hapus transit</button><?php endif; ?></div></div><?php if ($flash !== ''): ?><p class="flash" role="status"><?= e($flash) ?></p><?php endif; ?><div class="table-wrap"><table><thead><tr><th>No.</th><th>Resi</th><th>Isi paket</th><th>Kurir</th><th>Waktu</th><th>Lokasi terakhir</th></tr></thead><tbody><?php foreach ($rows as $index => $row): ?><tr><td><?= $index + 1 ?></td><td><?= e($row['nomor_resi']) ?></td><td><?= e($row['nama_barang']) ?></td><td><?= e($row['kurir']) ?></td><td><?= e($row['tanggal_jam_pengiriman']) ?></td><td><?= e($row['posisi_terakhir']) ?></td></tr><?php endforeach; ?><?php if (!$rows): ?><tr><td colspan="6">Belum ada data transit.</td></tr><?php endif; ?></tbody></table></div></main><?php if ($roleId === 'RL-001'): ?><dialog id="delete-dialog"><form method="post" action="../../controller/login/deleteData.php"><h2>Hapus data transit</h2><p>Tindakan ini menghapus semua transit untuk resi terpilih.</p><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><label for="delete-resi">Nomor resi</label><input id="delete-resi" name="nomor_resi" pattern="RS-[0-9]{7}" maxlength="10" required><div class="actions"><button class="secondary" formmethod="dialog">Batal</button><button class="danger" type="submit">Hapus</button></div></form></dialog><?php endif; ?></body></html>
